apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: shop-app
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
      - name: shop-db
        image: mysql:5.7
        ports:
          - containerPort: 3306
        envFrom:
          - secretRef:
              name: database-secret
              optional: false
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data